// dummy-rooms.js (또는 기존 파일 업데이트)

export const DummyRooms = [
  {
    id: "1",
    code: "E24QC45",
    title: "카페 BGM",
    hostNickname: "aryu_1217",
    hostAvatarUrl: "/default-avatar.jpg",
    isPrivate: false,
    tags: ["Chill", "K-POP"],
    listenersCount: 8,
    thumbnail: "/room-dummy-img/room-img1.png",
  },
  {
    id: "2",
    code: "V24RC28",
    title: "헬스장 근손실방지",
    hostNickname: "큐돌이",
    hostAvatarUrl: "/default-avatar.jpg",
    isPrivate: true,
    tags: ["EDM", "Pump"],
    listenersCount: 5,
    thumbnail: "/room-dummy-img/room-img2.png",
  },
  {
    id: "3",
    code: "L54MY93",
    title: "잔잔한 공부방",
    hostNickname: "Dj1212",
    hostAvatarUrl: "/default-avatar.jpg",
    isPrivate: false,
    tags: ["Lo-Fi", "Study"],
    listenersCount: 52,
    thumbnail: "/room-dummy-img/room-img3.png",
  },
  {
    id: "4",
    code: "L54MY93",
    title: "잔잔한 공부방2",
    hostNickname: "Dj1212",
    hostAvatarUrl: "/default-avatar.jpg",
    isPrivate: false,
    tags: ["Lo-Fi", "Study"],
    listenersCount: 52,
    thumbnail: "/room-dummy-img/room-img3.png",
  },
  {
    id: "5",
    code: "L54MY93",
    title: "잔잔한 공부방3",
    hostNickname: "Dj1212",
    hostAvatarUrl: "/default-avatar.jpg",
    isPrivate: false,
    tags: ["Lo-Fi", "Study"],
    listenersCount: 52,
    thumbnail: "/room-dummy-img/room-img3.png",
  },
];
